
[[nutch]]
== Apache Nutch
Plugin for Apache Nutch to index content using crawler.

[[nutch-installation]]
=== Installation
Turing support Apache Nutch 1.12 and 1.8 only, so go to https://viglet.com/turing/download/ and click on "Integration > Apache Nutch" link to download the turing-nutch-`<NUTCH_RELEASE>`-bin.zip.

1. Extract turing-nutch-`<NUTCH_RELEASE>`-bin.zip file into /appl/viglet/turing/nutch.
+
```shell
mkdir -p /appl/viglet/turing/nutch
unzip turing-nutch.zip -d /appl/viglet/turing/nutch
```
+
2. Download and install Apache Nutch 1.12 or 1.18 binary into http://nutch.apache.org > Downloads > apache-nutch-`<NUTCH_RELEASE>`-bin.tar.gz.
+
```shell
mkdir -p /appl/apache/
cp apache-nutch-<NUTCH_RELEASE>-bin.tar.gz /appl/apache
cd /appl/apache
tar -xvzf apache-nutch-<NUTCH_RELEASE>-bin.tar.gz
ln -s apache-nutch-<NUTCH_RELEASE>-bin nutch
```
+
3. Copy the Turing Plugin to Apache Nutch.
+
```shell
cp -R /appl/viglet/turing/nutch/indexer-viglet-turing /appl/apache/nutch/plugins
cp -f /appl/viglet/turing/nutch/conf/* /appl/apache/nutch/conf/
```
+

<<<

[[nutch-configuration]]
=== Configuration

[[nutch-configuration-112]]
==== Nutch 1.12
This step is only for Apache Nutch 1.12. Edit the /appl/apache/nutch/conf/nutch-site.xml, add or modify the following properties:

```xml
<property>
  <name>solr.server.url</name>
  <value>http://127.0.0.1:2700/Sample</value>
  <description>
      Turing URL + "/" + Turing Semantic Navigation Site.
  </description>
</property>
<property>
  <name>turing.url</name>
  <value>http://127.0.0.1:2700</value>
  <description>
      Defines the Turing URL into which data should be indexed using the
      indexer-turing plugin.
  </description>
</property>
<property>
  <name>turing.site</name>
  <value>Sample</value>
  <description>
      Defines the Turing Semantic Navigation Site.
  </description>
</property>
<property>
  <name>turing.auth</name>
  <value>true</value>
  <description>
      Whether to enable HTTP basic authentication for communicating with Turing. Use the username and password properties to configure your credentials.
  </description>
</property>
<property>
  <name>turing.username</name>
  <value>admin</value>
  <description>
      The username of Turing server.
  </description>
</property>
<property>
  <name>turing.password</name>
  <value>admin</value>
  <description>
      The password of Turing server.
  </description>
</property>
<property>
  <name>turing.timestamp.field</name>
  <value>modification_date</value>
  <description>
      Field used to store the timestamp of indexing. The default value is "tstamp".
  </description>
</property>
<property>
  <name>turing.field.type</name>
  <value>Page</value>
  <description>
      Type of Content. The default value is "Page".
  </description>
</property>
<property>
  <name>turing.field.source_app</name>
  <value>Nutch</value>
  <description>
      Name of Source Application. The default value is "Nutch".
  </description>
</property>
<!--
<property>
  <name>turing.field.hello</name>
  <value>foo</value>
  <description>
      This a test.
  </description>
</property>
<property>
  <name>turing.field.world</name>
  <value>bar</value>
  <description>
      This is another test.
  </description>
</property>
-->
```

<<<
[[nutch-configuration-112-timestamp-field]]
=====  Field with Timestamp

Can specify what is the field will be used to store the timestamp of indexing. The default value is `tstamp`. So modify the value of `turing.timestamp.field` property into nutch-site.xml:

```xml
<property>
  <name>turing.timestamp.field</name>
  <value>modification_date</value>
  <description>
      Field used to store the timestamp of indexing. The default value is "tstamp".
  </description>
</property>
```

[[nutch-configuration-112-source-app-field]]
=====  Source App Name

Turing AI Semantic Navigation Site allows to index content from many sources, so can identify where the content was indexed, can specify the name of the source changing the `turing.field.source_app` into nutch-site.xml file. The default value is `Nutch`:

```xml
<property>
  <name>turing.field.source_app</name>
  <value>Nutch</value>
  <description>
      Name of Source Application. The default value is "Nutch".
  </description>
</property>
```
<<<
[[nutch-configuration-112-fixed-fields]]
=====  Fixed Fields

To create new fixed field during indexing, add new properties with prefix `turing.field` + `name of new custom field` into nutch-site.xml file, for example:

```xml
<property>
  <name>turing.field.hello</name>
  <value>foo</value>
  <description>
      This a test.
  </description>
</property>
<property>
  <name>turing.field.world</name>
  <value>bar</value>
  <description>
      This is another test.
  </description>
</property>
```
IMPORTANT: Need add these fields to Solr schema.xml file and create them in Semantic Navigation Site > Fields

<<<
[[nutch-configuration-112-parameters]]
===== Parameters
Modify the following parameters:

.nutch-site.xml parameters
[%header,cols=3*] 
|===
| Parameter | Description | Default value
| solr.server.url | Turing URL + "/" + Turing Semantic Navigation Site. | -
| turing.url | Defines the fully qualified URL of Turing AI into which data should be indexed. | http://localhost:2700
| turing.site | Turing Semantic Navigation Site Name. |  Sample
| turing.weight.field | Field's name where the weight of the documents will be written. If it is empty no field will be used. | -
| turing.auth | Whether to enable HTTP basic authentication for communicating with Turing AI. Use the `username` and `password` properties to configure your credentials. | true
| turing.username | The username of Turing AI server. | admin
| turing.password | The password of Turing AI server. | admin
| turing.timestamp.field | Field used to store the timestamp of indexing. | tstamp
| turing.field.`FIELD_NAME` | Modify or create a custom field during indexing. | -
|===
<<<

[[nutch-configuration-118]]
==== Nutch 1.18
This step is only for Apache Nutch 1.18. Edit the /appl/apache/nutch/conf/index-writers.xml

```xml
<writers xmlns="http://lucene.apache.org/nutch" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://lucene.apache.org/nutch index-writers.xsd">
 <writer id="indexer_viglet_turing_1"
		class="com.viglet.turing.nutch.indexwriter.TurNutchIndexWriter">
		<parameters>
			<param name="url" value="http://localhost:2700" />
			<param name="site" value="Sample" />
			<param name="commitSize" value="1000" />
			<param name="weight.field" value=""/>
			<param name="auth" value="true" />
			<param name="username" value="admin" />
			<param name="password" value="admin" />
		</parameters>
		<mapping>
			<copy>
				<field source="content" dest="text"/>
				<!-- <field source="title" dest="title,search"/> -->
			</copy>
			<rename>
				<field source="metatag.description" dest="description" />
				<field source="metatag.keywords" dest="keywords" />
				<field source="metatag.charset" dest="charset" />
			</rename>
			<remove>
				<field source="segment" />
				<field source="boost" />
			</remove>
		</mapping>
	</writer>
</writers>
```
<<<

[[nutch-configuration-118-parameters]]
===== Parameters
Modify the following parameters:

.index-writers.xml parameters
[%header,cols=3*] 
|===
| Parameter | Description | Default value
| url | Defines the fully qualified URL of Turing AI into which data should be indexed. | http://localhost:2700
| site | Turing Semantic Navigation Site Name. |  Sample
| weight.field | Field's name where the weight of the documents will be written. If it is empty no field will be used. | -
| commitSize | Defines the number of documents to send to Turing AI in a single update batch. Decrease when handling very large documents to prevent Nutch from running out of memory.

**Note**: It does not explicitly trigger a server side commit. | 1000
| auth | Whether to enable HTTP basic authentication for communicating with Turing AI. Use the `username` and `password` properties to configure your credentials. | true
| username | The username of Turing AI server. | admin
| password | The password of Turing AI server. | admin
|===

<<<
[[nutch-index-website]]
=== Index a Website

[[nutch-index-website-nutch-command-line]]
==== Nutch Command Line
There are many ways to index a website using Apache Nutch. Learn more at https://cwiki.apache.org/confluence/display/nutch/NutchTutorial.

For example, a simple way to index https://viglet.com:

1. Nutch expects some seed URLs from where to start the crawling.
+
```shell
cd /appl/apache/nutch/
mkdir urls
echo "https://viglet.com" > urls/seed.txt
```
+
TIP: You can also limit crawling to a certain hostname etc. by setting a regular expression in `/appl/apache/nutch/runtime/local/config/regex-filter.txt`

2. Index the content with Turing AI
+
```shell
# 1.12
cd /appl/apache/nutch/
bin/crawl -i urls/ crawl-output/ 5

# 1.18
cd /appl/apache/nutch/
bin/crawl -i -s urls/ crawl-output/ 5
```
<<<
+
or with parameter, for instance:
+
```shell
# 1.12 (Alternative 1)
cd /appl/apache/nutch/
bin/crawl -D turing.force.config=true -D turing.site="Sample_EN" -i urls/ crawl-output/ 5

# 1.12 (Alternative 2)
cd /appl/apache/nutch/
bin/crawl -D solr.server.url="http://localhost:2700/Sample_EN" -i urls/ crawl-output/ 5

# 1.18
cd /appl/apache/nutch/
bin/crawl -D turing.site="Sample_EN" -i -s urls/ crawl-output/ 5
```
+
.crawl Parameters
[%header,cols=3*] 
|===
| Parameter | Example  | Description
| -D solr.server.url | -D solr.server.url="http://localhost:2700/Sample" | Turing URL + "/" + Turing Semantic Navigation Site.
| -D turing.force.config | -D turing.force.config=true  | Use turing.url and turing.site instead of solr.sever.url
| -D turing.url | -D turing.url="localhost:2700" | Defines the fully qualified URL of Turing AI into which data should be indexed.
| -D turing.site | -D turing.url="Sample" | Turing Semantic Navigation Site Name.
| -D turing.auth  | -D turing.auth=false  | Whether to enable HTTP basic authentication for communicating with Turing AI. Use the `username` and `password` properties to configure your credentials.
| -D turing.username  | -D turing.username="admin" | The username of Turing AI server.
| -D turing.password  | -D turing.password="admin" | The password of Turing AI server.
|===

<<<
[[nutch-index-website-nutch-provider-for-wem]]
==== Nutch Provider for WEM
Web Experience Management, version 16.2 includes an example of a Page Searchable Provider using Apache Nutch, the installation and configuration is described at http://webapp.opentext.com/piroot/wcmgt/v160200/wcmgt-aci/en/html/jsframe.htm?nutch-provider-config

You can use the same Nutch Provider for InfoFusion (`com.vignette.as.server.pluggable.service.pagesearch.nutch.NutchProvider`), but using the Nutch with Turing Plugin. 
In Nutch Provider Configuration at WEM Configuration Console, change the variables below:

* SOLR_URL: Fill with Turing URL, for example, http://localhost:2700, instead of Solr URL;
* NUTCH_CONFIGURATION: In the XML file, put the name Turing Semantic Navigation Site in the `core` attribute, for example: 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<nutch-config
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xmlns="http://www.vignette.com/xmlschemas/nutch-config"
		xsi:schemaLocation="http://www.vignette.com/xmlschemas/nutch-config nutch-config.xsd">
	<default crawlId="WEM_default" core="Sample"/>
	<configuration crawlId="WEM_en" core="Sample_EN">
		<locale name="en"/>
		<locale name="en_US"/>
	</configuration>
	<configuration crawlId="WEM_es" core="Sample_ES">
		<locale name="es"/>
	</configuration>
	<configuration crawlId="WEM_de" core="Sample_DE">
		<locale name="de"/>
	</configuration>
	<configuration crawlId="WEM_fr" core="Sample_FR">
		<locale name="fr"/>
	</configuration>
	<configuration crawlId="WEM_it" core="Sample_IT">
		<locale name="it"/>
	</configuration>
</nutch-config>
```