[[wem]]
== OpenText WEM Listener
OpenText WEM Listener to publish content to Viglet Turing

[[wem-installation]]
=== Installation

[[wem-download]]
==== Download
Go to https://viglet.com/turing/download/ and click on "Integration > WEM Listener" link to download it.

Extract the turing-wem.zip file to /appl/viglet/turing/wem

```shell
mkdir -p /appl/viglet/turing/wem
unzip turing-wem.zip -d /appl/viglet/turing/wem
```

[[wem-classpath]]
==== Classpath
1. Copy the  turing-wem-all.jar to WEM and CDS Library directory, for example:
+
```shell
cp /appl/viglet/turing/wem/turing-wem-all.jar /appl/ot/WEM/Content/<VERSION>/lib/
```
+
2. Edit the `cda.classpath` file of Management and Delivery Stages, for examples:
+
```shell
/appl/otwork/WEM/inst-vgninst/cfgagent/vcm-vgninst/cdsvcs/stage-mgmt/cds-mgmt/cda-mgmt/conf/cda.classpath
/appl/otwork/WEM/inst-vgninst/cfgagent/vcm-vgninst/cdsvcs/stage-Live/cds-Live/cda-Live/conf/cda.classpath
```
+
3. These cda.classpath files contain the following lines:
+
```properties
CLASSPATH.6=\#INSTALL_DIR\#/lib/jaxws
CLASSPATH.5=\#INSTALL_DIR\#/lib
CLASSPATH.4=\#INSTALL_DIR\#/lib/appsvcsda/jsp-api.jar
CLASSPATH.3=\#INSTALL_DIR\#/lib/appsvcsda/vgn-appsvcs-dadataobject.jar
CLASSPATH.2=\#INSTALL_DIR\#/lib/jax-qname.jar
CLASSPATH.1=\#INSTALL_DIR\#/jdbc
```
+
4. Add the following line in each cda.classpath
+
```properties
CLASSPATH.7=\#INSTALL_DIR\#/lib/turing-wem-all.jar
```
+


<<<

[[wem-deploy]]
==== WEM Deploy

Add the turing-wem-all.jar into WEM using configp:

....
$ ./configp
============================================================

Configuration Program Main Menu

-----------------------------------------
   1.  Connect to WEM Server
   2.  Create a Disconnected Configuration Agent
   3.  Remove a Disconnected Configuration Agent
   4.  Repair Management Server

   q.  Quit

   > 1
============================================================
Connect to WEM Server: WEM Server Connection Information


WEM Server host: wemserver
WEM Server port: 27110
WEM Server administrator: vgnadmin
WEM Server administrative password:

*****************************************
 You have entered the following:

  WEM Server host = wemserver
  WEM Server port = 27110
  WEM Server administrator = vgnadmin
  WEM Server administrative password = ********


Is this correct ( (y)es, (n)o, (b)ack, (c)ancel )?[y]:
Connecting...
Connected to t3://wemserver:27110
============================================================

Managing Configuration Services
-----------------------------------------
   1.  Manage a Product Instance
   2.  Create a Configuration Agent
   3.  Remove a Configuration Agent
   4.  Register a Configuration Agent
   5.  Manage Applications
   6.  List Configuration Settings

   b.  Back
   q.  Quit

   > 5
============================================================
Manage Applications: Manage Application


  To register or unregister Extension Modules, select
  Register Product Extensions. To modify an existing
  deployed application, select Update Runtime Services.

Select type of application update
---------------------------------
   1.  Register Product Extensions
   2.  Update Runtime Services

   b.  Back
   c.  Cancel

   > 1

*****************************************
 You have entered the following:

  Select type of application update = Register Product Extensions


Is this correct ( (y)es, (n)o, (b)ack, (c)ancel, (u)ndo )?[y]:
============================================================
Manage Applications: Deployment Types


  You can choose to deploy an extension which exists
  within the VCM ear container or a standalone application
  outside of the VCM ear container.

Do you want to deploy an extension or standalone application?
--------------------------------------------------
   1.  Extension
   2.  Standalone Application

   b.  Back
   c.  Cancel

   > 1

*****************************************
 You have entered the following:

  Do you want to deploy an extension or standalone application? = Extension


Is this correct ( (y)es, (n)o, (b)ack, (c)ancel, (u)ndo )?[y]:
============================================================
Manage Applications: Deployment Actions


Register Extension Type
-----------------------
   1.  JAR Extension Module
   2.  WAR Extension Module
   3.  Multiple Extension Modules - can include both JAR and WAR files

   b.  Back
   c.  Cancel

   > 1
Deployment Action
-----------------
   1.  Deploy Extension
   2.  Undeploy Extension

   b.  Back
   c.  Cancel

   > 1

*****************************************
 You have entered the following:

  Register Extension Type = jarext (JAR Extension Module)
  Deployment Action = Deploy Extension


Is this correct ( (y)es, (n)o, (b)ack, (c)ancel, (u)ndo )?[y]:
============================================================
Manage Applications: Extension JAR Path


  Enter the path to the archive file containing the
  extension. This file is registered with the repository
  and deployed to the application server.

  Important!! Deployment of an extension could take
  up to 15 mins.

JAR Path (example: C:\vign_extn.jar): /appl/viglet/turing/wem/turing-wem-all.jar

*****************************************
 You have entered the following:

  JAR Path (example: C:\vign_extn.jar) = /appl/viglet/turing/wem/turing-wem-all.jar


Is this correct ( (y)es, (n)o, (b)ack, (c)ancel, (u)ndo )?[y]: y
============================================================
Manage Applications: Confirm Configuration


  Are you ready to perform this action?



Continue? ( (y)es, (n)o, (b)ack, (c)ancel )? [y]: y

Confirm Configuration:

  All the information has been collected. Would you
  like to commit the configuration? (y/n) [y]: y

Step 1 of 3: Validating Input ...
Step 2 of 3: Check Configuration Status ...
Step 3 of 3: Updating Application ...

Success:

The configuration wizard completed successfully.

....



<<<

[[wem-resource]]
==== Resource
Access the Configuration Console (http://wem_host:wem_port/configconsole) and add the VigletTuring Generic Resource in each Delivery Stage that will index to Turing Semantic Navigation.

For example: 

1. Click on right-button on `Configuration Console > Content > Delivery Services > Content Delivery Stage - Live > Resources`, select Add Resource
2. In Resource Type, select "Generic Resource" and click Next
3. In Resource Name, type: `VigletTuring` and click Next
4. In Generic Resource Type, select "Other(Any stage-specific resource subtype information)" and click Next
5. In Resource Subtype, type: `Properties` and click Next
6. In Resource Information > Non-Encrypted Data type: `fill later` and Encrypted Data leaves blank and click Next
7. In Confirm Configuration click Finish.
8. Edit "Configuration Console > Content > Delivery Services > Content Delivery Stage - SebraeNA > Resources > Resource Type - Generic > Resource - VigletTuring > Generic Resource > DATA" and replace "fill later" for:
```properties
turing.url=http://localhost:2700
turing.mappingsxml=/appl/viglet/turing/wem/conf/CTD-Turing-Mappings.xml
turing.login=admin
turing.password=admin
turing.provider.name="WEM"

dps.config.association.priority=SampleSite
dps.config.filesource.path=/opentext/otwork/WEM/inst-vgninst/file_source

dps.site.default.urlprefix=http://mywemsite.example.com
dps.site.default.contextname=sites
dps.site.default.sn.site=Sample
dps.site.default.sn.locale=en_US
dps.site.default.en.sn.site=SampleEN

dps.site.Intranet.urlprefix=http://intranet.example.com
dps.site.Intranet.contextname=sites
dps.site.Intranet.sn.site=Intra
dps.site.Intranet.sn.locale=en_US
dps.site.Intranet.it_IT.sn.locale=it
dps.site.Intranet.es.sn.site=IntraES

```

<<<
Where

.VigletTuring Generic Resource Properties
[%header,cols=3*] 
|===
| Parameter | Required | Description
| turing.url | yes | Turing URL.
| turing.mappingsxml | yes | XML File.
| turing.login | yes | Turing Login.
| turing.password | yes | Turing Password.
| turing.provider.name | yes | Provider Identifier that will be send to Turing during the indexing.
| dps.config.association.priority | no | If the content is associated with more than one site, you can define which site will be chosen to avoid conflict.
| dps.config.filesource.path | yes |Used when processing a file using `com.viglet.turing.wem.ext.TurStaticFile`, in order to locate the file in the file sytem.
| dps.site.default.urlprefix | no | Prefix will be used to create URL of content in Search.
| dps.site.default.contextname | no | Context Name of DPS.
| dps.site.default.sn.site | yes | Name of site on Turing Semantic Navigation, that will be used to index the WEM Content.
| dps.site.default.sn.locale | no | If the content has no locale attribute, you can specify a default Semantic Navigation Site that will be indexed.
| dps.site.default.<locale>.sn.site | no | If the content has locale attribute, you can specify a different Semantic Navigation Site that will be indexed.
| dps.site.<site>.urlprefix | no | Prefix will be used to create URL of content in Search for specific site.
| dps.site.<site>.contextname | no | Context Name of DPS for specific site.
| dps.site.<site>.sn.site | no | Name of site on Turing Semantic Navigation for specific site, that will be used to index the WEM Content.
| dps.site.<site>.sn.locale | no | If the content for specific site has no locale attribute, you can specify a default Semantic Navigation Site that will be indexed.
| dps.site.<site>.<locale>.sn.locale | no | If the content of a specific site has a locale attribute, you can change the current locale to a new one that will be indexed.
| dps.site.<site>.<locale>.sn.site | no | If the content for specific site has locale attribute, you can specify a different Semantic Navigation Site that will be indexed.
|===

NOTE: Repeat this procedure in other Management and Delivery Stages that will use Turing Semantic Navigation

IMPORTANT: The Listener uses URL Scheme from Site to generate Content URL.

<<<

[[wem-events]]
==== Events
Access the Configuration Console (http://wem_host:wem_port/configconsole) and add the EventListener in each Delivery Stage that will index to Turing Semantic Navigation.

Configure the Event listeners.

1. Register the required listeners to the events as specified below:
** `Configuration Console > Content > Delivery Services > Content Delivery Stage - Live > Content Delivery Services - Live > Application Services > Events > Deployment.ManagedObjectCreate`
+
....
com.viglet.turing.wem.listener.DeploymentEventListener
....

+
** `Configuration Console > Content > Delivery Services > Content Delivery Stage - Live > Content Delivery Services - Live > Application Services > Events > Deployment.ManagedObjectUpdate`
+
....
com.viglet.turing.wem.listener.DeploymentEventListener
....
+
**	`Configuration Console > Content > Delivery Services > Content Delivery Stage - Live > Content Delivery Services - Live > Application Services > Events > PrePersistence.Delete`
+
....
com.viglet.turing.wem.listener.PrePersistenceEventListener
....
NOTE: Be sure to copy any existing listeners from the current run value and append the new listener to    the end of the list during registration. If needed, see section 6 of the Management Console Extensibility SDK guide for more information on registering event listeners.
+
2. Commit the configuration changes and restart the DA

[[wem-command-line]]
==== Command Line

Copy `/appl/viglet/turing/wem/command-line/<WEM_VERSION>/turing-wem` to `<WEM_DIR>/bin`, it works a lot like `vgncontentindex` command line.

[%header,cols=5*] 
|===
| Parameter | Alternative Parameter | Required | Default | Description
| --all | -a | No | false | Index all instances of all content types and object types.
| --content-type | -c | No | - | The XML name of the content type or object type whose instances are to be indexed.
| --debug | - | No |- | Change the log level to debug
| --guids | -g | No |- | The path to a file containing the GUID(s) of content instances or static files to be indexed.
| --help | - | No | - |  Print usage instructions
| --host | -h | Yes | - | The host on which Content Management server is installed.
| --page-size | -z | No | 500 | The page size. After processing a page the processed count is written to an offset file. This helps the indexer to resume from that page even after failure.
| --password | -p | No | - | The password for the user name.
| --siteName | -s | Yes | Sample | WEM site name.
| --username | -u | Yes | - | A username to log in to the Content Management Server.
| --working-dir | -w | Yes | - | The working directory where the vgncfg.properties file is located.
|===

IMPORTANT: The ~/OpenText/turing-wem.log is always created during command line execution.

<<<

[[wem-configuration-mapping]]
=== Mapping

Create a /appl/viglet/turing/wem/conf/CTD-Turing-Mappings.xml file with the following lines:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<mappingDefinitions>
    <common-index-attrs>
        <srcAttr className="com.viglet.turing.wem.ext.TurCTDName" mandatory="true">
            <tag>type</tag>
        </srcAttr>
        <srcAttr className="com.viglet.turing.wem.ext.TurWEMPublicationDate" mandatory="true">
            <tag>publication_date</tag>
        </srcAttr>
        <srcAttr className="com.viglet.turing.wem.ext.TurWEMModificationDate" mandatory="true">
            <tag>modification_date</tag>
        </srcAttr>
        <srcAttr className="com.viglet.turing.wem.ext.TurSiteName" mandatory="true">
            <tag>site</tag>
        </srcAttr>
        <srcAttr className="com.viglet.turing.wem.ext.HTML2Text">
            <tag>text</tag>
        </srcAttr>
        <srcAttr className="com.viglet.turing.wem.ext.HTML2Text">
            <tag>abstract</tag>
        </srcAttr>
        <srcAttr className="com.viglet.turing.wem.ext.DPSUrl" mandatory="true">
            <tag>url</tag>
        </srcAttr>
    </common-index-attrs>
    <mappingDefinition contentType="INNOVATE_PRESS_RELEASE">
        <index-attrs>
            <srcAttr xmlName="title">
                <tag>title</tag>
            </srcAttr>
            <srcAttr xmlName="teaser">
                <tag>abstract</tag>
            </srcAttr>
            <srcAttr xmlName="body">
                <tag>text</tag>
            </srcAttr>
            <srcAttr textValue="foo bar">
                <tag>text</tag>
            </srcAttr>
            <srcAttr xmlName="image" className="com.viglet.turing.wem.ext.TurStaticFile">
                <tag>text</tag>
            </srcAttr>
        </index-attrs>
    </mappingDefinition>
</mappingDefinitions>
```
NOTE: There should be a srcAttr element for each content type field to be indexed by Turing AI.  The xmlName attribute should contain the XML Name of the relevant field.

<<<

[[wem-xml-elements]]
=== CTD-Turing-Mappings.xml Elements
The following sections describe the delements defined in the CTD-Turing-Mappings.xml file under the root element `<mappingDefinitions>`:

[[wem-xml-elements-common-index-attrs]]
==== common-index-attrs

.srcAttr (common-index-attrs) Element Definition
[%header,cols=2*] 
|===
| Element | Description 
| srcAttr | List of tags (turing fields) that can be used by CTDs in mappingDefinition.   
|===

.srcAttr (common-index-attrs) Attributes
[%header,cols=4*] 
|===
| Attribute | Required/ Optional | Default Value | Description
| mandatory | Optional | "false" | If "true", it means the tag will always be inserted in all CTDS.
| classname | Required | - | Custom class to process the field value. Implicitly define this custom class to process the field value className in mappingDefinition srcAttr when the same tag is used.
|===

<<<

[[wem-xml-elements-mapping-definition]]
==== mappingDefinition

.mappingDefinition Element Definition
[%header,cols=2*] 
|===
| Element | Description
| mappingDefinition | CTD Mapping.
|===

.mappingDefinition Attribute
[%header,cols=4*] 
|===
| Attribute | Required/ Optional | Default Value | Description
| contentType | Required | - | Content Type XML Name.
|===

.index-attrs Element Definition
[%header,cols=2*] 
|===
| Element | Description
| index-attrs | List of Content Type Field
|===

.srcAttr (mappingDefinition) Element Definitiion
[%header,cols=2*] 
|===
| Element | Description
| srcAttr | Content Type Field to be indexed by Turing AI.  
|===

.srcAttr (mappingDefinition) Attributes
[%header,cols=4*] 
|===
| Attribute | Required/ Optional | Default Value | Description
| xmlName | Required (if className or textValue is missing) | - | Content Type Field XML Name.
| relation | Required (if xmlName is missing) | - | Content Type Relation XML Name.
| uniqueValues | Optional | "false" | A List return unique values.
| valueType | Optional | - | If "html" then convert HTML to Text.
| classname | Required (if xmlName or textValue is missing) | - | Custom class to process the field value.
| textValue | Required (if xmlName or classname is missing) | - | returns a text for the tag (Turing field)
|===

.tag Element Definition
[%header,cols=2*] 
|===
| Element | Element Description
| tag | Turing AI Semantic Navigation Field
|===

<<<

[[wem-xml-extensions]]
=== Extensions

There are ready-made extensions to be used when indexing WEM content through the Turing Listener.

.Extensions 
[%header,cols=2*] 
|===
| Plugin | Description
| com.viglet.turing.wem.ext.TurCTDName | Content Type Name.
| com.viglet.turing.wem.ext.TurWEMPublicationDate | Publication Date of Content Instance, if not exist use Modification Date.
| com.viglet.turing.wem.ext.TurWEMModificationDate | Modification Date of Content Instance.
| com.viglet.turing.wem.ext.TurSiteName | Site name associated.
| com.viglet.turing.wem.ext.TurHTML2Text | Convert HTML to Text.
| com.viglet.turing.wem.ext.TurDPSUrl | DPS URL based on URL Scheme.
| com.viglet.turing.wem.ext.TurSpotlightExtraFields | Extract attributes of Spotlight Content Instance.
| com.viglet.turing.wem.ext.TurChannelDescription | Channel Description.
| com.viglet.turing.wem.ext.TurChannelPageName | Name of Channel Page.
| com.viglet.turing.wem.ext.TurChannelPageUrl | URL of Channel Page.
| com.viglet.turing.wem.ext.TurChannelPath | Channel Path.
| com.viglet.turing.wem.ext.TurParentChannel | Parent Channel of Content Instance.
| com.viglet.turing.wem.ext.TurStaticFile | Get WEM ID from defined attribute and convert to file://<path_of_file>, using the `dps.config.filesource.path` properties of `VigletTuring Resource`. This extension modifies the listener workflow, as it adds the files of this content instance to the zip file along with export.json and sends it to the Turing AI, which will process these files and add the content in the attributes of export.json, before its indexing.
|===

[[wem-spotlight]]
=== Spotlight

The Turing AI Semantic Navigation Site allows you to create spotlights that will be highlighted in the search, based on the registered terms.
There are two types of Spotlight:

* Managed - Manipulated on the Turing AI console.
* Unmanaged - Created externally and not manipulated in the Turing AI console.

In this case, it is possible to create Unmanaged Spotlights using WEM, creating a CTD and whenever handled Content Instances of this CTD, the WEM Listener will send this Content and the Turing AI will treat this content with a different flow, which will allow creating new Unmanaged Spotlight.
For this, you need to import the Spotlight CTD into WEM using the following command line, for example:

```shell
$ ./vgnimport -h localhost:27110 -u vgnadmin -p vgnadmin -f /appl/viglet/turing/wem/imports/turing-ctd.zip -l /appl/viglet/turing/wem/imports/turing-ctd.log
```
In /appl/viglet/turing/wem/conf/CTD-Turing-Mappings.xml file you need to add the following lines:

```xml
<mappingDefinition contentType="TUR_SPOTLIGHT">
    <index-attrs>
        <srcAttr xmlName="NAME-TUR-SPOTLIGHT">
            <tag>name</tag>
        </srcAttr>
        <srcAttr xmlName="TERMS-TUR-SPOTLIGHT">
            <tag>terms</tag>
        </srcAttr>
        <srcAttr relation="WEMSYS-TUR-SPOTLIGHT-CONTENT" className="com.viglet.turing.wem.ext.TurSpotlightExtraFields">
            <tag>content</tag>
        </srcAttr>
    </index-attrs>
</mappingDefinition>
```

IMPORTANT: Need to configure Turing Listener in WEM as described in this documentation.

