= Viglet Turing AI: Developer Guide
Viglet Team <opensource@viglet.com>
:page-layout: documentation
:organization: Viglet Turing
ifdef::backend-pdf[:toc: left]
:toclevels: 5
:toc-title: Table of Content
:doctype: book
:revnumber: 0.3.4
:revdate: 05-08-2021
:source-highlighter: rouge
:pdf-theme: viglet
:pdf-themesdir: {docdir}/../themes/
:page-breadcrumb-title: Developer Guide
:page-permalink: /turing/developer-guide/
:imagesdir: ../../
:page-pdf: /turing/turing-developer-guide.pdf
:page-product: turing

[preface]
= Preface

Viglet Turing AI (https://viglet.com/turing) is an open source solution (https://github.com/openturing), which has Semantic Navigation and Chatbot as its main features. You can choose from several NLPs to enrich the data. All content is indexed in Solr as search engine.

:numbered:

== Get Started

=== More Documentation

Technical documentation on Turing AI is available at https://docs.viglet.com/turing.

=== Development Structure

Turing AI was developed using Spring Boot for its backend.

The UI is currently using AngularJS, but a new UI is being developed using Angular 12 with CSS Primer.

By default it uses the H2 database, but can be changed to other databases using Spring Boot properties. It comes bundled with OpenNLP in the same JVM.

It uses Java 14 and its deployment is done with Gradle 7.2 and works on Linux and Windows.

To use Semantic Navigation and Chatbot you must have a Solr service available. If you prefer to work with all the services Turing depends on, you can use docker-compose to start these services, we use the Docker Desktop installed on computer.

In addition to Java 14, you also need to have Git and NodeJS installed.

We are using Eclipse, Visual Studio Code and IntelliJ as IDEs.

=== Download

Use the git command line to download the repository to your computer.

```shell
git clone https://github.com/openturing/turing.git
```

=== Run

To run Turing AI, just execute the following lines:

==== Turing Server

```shell
./gradlew turing-app:bootrun
```
==== New Turing UI

```shell
cd turing-ui

## Console
ng serve console

## Search
ng serve sn

## Chatbot
ng serve converse
```


=== Docker Compose

You can start the Turing AI using MariaDB, Solr and Nginx.

```shell
docker-compose up
```

=== URLs

* Administration Console: http://localhost:2700. (admin/admin)
* Semantic Navigation Sample: http://localhost:2700/sn/Sample.