= Viglet Turing AI: Developer Guide
Viglet Team <opensource@viglet.com>
:page-layout: documentation
:organization: Viglet Turing
ifdef::backend-pdf[:toc: left]
:toclevels: 5
:toc-title: Table of Content
:doctype: book
:revnumber: 0.3.4
:revdate: 05-08-2021
:source-highlighter: rouge
:pdf-theme: viglet
:pdf-themesdir: {docdir}/../themes/
:page-breadcrumb-title: Developer Guide
:page-permalink: /turing/developer-guide/
:imagesdir: ../../
:page-pdf: /turing/turing-developer-guide.pdf
:page-product: turing

[preface]
== Preface

Viglet Turing AI (https://viglet.com/turing) is an open source solution (https://github.com/openturing), which has Semantic Navigation and Chatbot as its main features. You can choose from several NLPs to enrich the data. All content is indexed in Solr as search engine.

:numbered:

== More Documentation

Technical documentation on Turing AI is available at https://docs.viglet.com/turing.

== Development Structure

=== Frameworks
Turing AI was developed using Spring Boot (https://spring.io/projects/spring-boot) for its backend.

The UI is currently using AngularJS (https://angularjs.org), but a new UI is being developed using Angular 12 (https://angular.io) with Primer CSS (https://primer.style/css).

In addition to Java, you also need to have Git (https://git-scm.com/downloads) and NodeJS (https://nodejs.org/en/download/) installed.

=== Databases
By default it uses the H2 database (https://www.h2database.com), but can be changed to other databases using Spring Boot properties. It comes bundled with OpenNLP (https://opennlp.apache.org/) in the same JVM.

=== Language and Deploy
It uses Java 14 (https://adoptopenjdk.net/archive.html?variant=openjdk14&jvmVariant=hotspot) and its deployment is done with Gradle 7.2 (https://gradle.org/) and works on Linux and Windows.

=== Docker
To use Semantic Navigation and Chatbot you must have a Solr (https://solr.apache.org) service available. If you prefer to work with all the services Turing depends on, you can use docker-compose (https://docs.docker.com/compose/install) to start these services, we use the Docker Desktop (https://www.docker.com/products/docker-desktop) installed on computer.

=== IDE
You can use Spring Tools 4 for Eclipse (https://spring.io/tools) or Eclipse (https://www.eclipse.org/downloads/) or Visual Studio Code (https://code.visualstudio.com/) or IntelliJ (https://www.jetbrains.com/pt-br/idea/) as IDEs.

== Download

Use the git command line to download the repository to your computer.

=== Turing Server and Connectors

```shell
git clone https://github.com/openturing/turing.git 
```
=== Turing Java SDK

```shell
git clone https://github.com/openturing/turing-java-sdk.git
```

== Run during Development

To run Turing AI, execute the following lines:

=== Turing Server

```shell
cd turing 
./gradlew turing-app:bootrun
```

=== New Turing UI

```shell
cd turing/turing-ui

## Console
ng serve console

## Search
ng serve sn

## Chatbot
ng serve converse
```
IMPORTANT: You need start the Turing Server and Solr first.

=== Java SDK

```shell
cd turing-java-sdk
./gradlew shadowJar
java -cp build/libs/turing-java-sdk-all.jar com.viglet.turing.client.sn.sample.TurSNClientSample
```

IMPORTANT: You need start the Turing Server and Solr first.

== Docker Compose

You can start the Turing AI using MariaDB, Solr and Nginx.

```shell
./gradlew turing-app:build -x test -i --stacktrace
docker-compose up
```
NOTE: If you have problems with permissions on directories, run `chmod -R 777 volumes`

== URLs

=== Turing Server
* Administration Console: http://localhost:2700. (admin/admin)
* Semantic Navigation Sample: http://localhost:2700/sn/Sample.

=== New Turing UI
* Console http://localhost:4200
* Search Page http://localhost:4200/sn/Sample
* Converse http://localhost:4200/converse

=== Docker Compose
* Administration Console: http://localhost. (admin/admin)
* Semantic Navigation Sample: http://localhost/sn/Sample.
* Solr: http://localhost:8983

=== Code Quality

You can check the quality of Turing Code at:

* SonarCloud at https://sonarcloud.io/organizations/viglet-turing/projects
* Github Actions at https://github.com/openturing/turing/actions
* Github Security at https://github.com/openturing/turing/security/code-scanning
* Codecov at https://app.codecov.io/gh/openturing/turing